# version: "3"

services:
  mlflow:
    build:
      context: .
      dockerfile: Dockerfile.mlflow
    container_name: mlflow_server
    ports:
      - "5000:5000"
    volumes:
      - ./mlflow_data:/home/mlflow_data
    networks:
      - ml_network

  airflow-init:
    build:
      context: .
      dockerfile: Dockerfile.airflow
    entrypoint: /bin/bash
    command:
      - -c
      - |
        mkdir -p /opt/airflow/logs /opt/airflow/dags /opt/airflow/plugins &&
        airflow db init &&
        airflow users create \
          --username admin \
          --firstname admin \
          --lastname admin \
          --role Admin \
          --email admin@example.com \
          --password admin
    user: "50000:0"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./airflow_home:/opt/airflow
    networks:
      - ml_network

  airflow-webserver:
    build:
      context: .
      dockerfile: Dockerfile.airflow
    depends_on:
      - airflow-init
    command: bash -c "airflow webserver"
    ports:
      - "8080:8080"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./airflow_home:/opt/airflow
    networks:
      - ml_network

  airflow-scheduler:
    build:
      context: .
      dockerfile: Dockerfile.airflow
    depends_on:
      - airflow-init
    command: bash -c "airflow scheduler"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./airflow_home:/opt/airflow
    networks:
      - ml_network

networks:
  ml_network:
    driver: bridge
