FROM python:3.12-slim

RUN pip install --no-cache-dir mlflow pandas scikit-learn xgboost pyarrow

EXPOSE 5000

CMD ["mlflow", "server", "--host", "0.0.0.0", "--port", "5000", \
     "--backend-store-uri", "sqlite:///home/mlflow_data/mlflow.db" ]
